/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CannotAccessVerifyStamp: typeof import('./src/components/elements/CannotAccessVerifyStamp.vue')['default']
    CommonContact: typeof import('./src/components/common/CommonContact.vue')['default']
    CommonCustomerProfile: typeof import('./src/components/common/CommonCustomerProfile.vue')['default']
    CommonFooter: typeof import('./src/components/common/CommonFooter.vue')['default']
    CommonSlider: typeof import('./src/components/common/CommonSlider.vue')['default']
    CommonStatusVerify: typeof import('./src/components/elements/CommonStatusVerify.vue')['default']
    ContactStack: typeof import('./src/components/templates/verifies/TemplateThree/ContactStack.vue')['default']
    CustomerProfile: typeof import('./src/components/common/CustomerProfile.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FormVerification: typeof import('./src/components/elements/FormVerification.vue')['default']
    HomeStack: typeof import('./src/components/templates/verifies/TemplateThree/HomeStack.vue')['default']
    NewStampCode: typeof import('./src/components/common/NewStampCode.vue')['default']
    OldQrcodeTemplate: typeof import('./src/components/templates/verifies/OldQrcodeTemplate.vue')['default']
    ProductDetail: typeof import('./src/components/common/ProductDetail.vue')['default']
    ProductItem: typeof import('./src/components/common/ProductItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialChannel: typeof import('./src/components/elements/SocialChannel.vue')['default']
    StampCodeBlocked: typeof import('./src/components/common/StampCodeBlocked.vue')['default']
    StampStatusVerification: typeof import('./src/components/elements/StampStatusVerification.vue')['default']
    StampUnauthorized: typeof import('./src/components/elements/StampUnauthorized.vue')['default']
    StatusVerification: typeof import('./src/components/elements/StatusVerification.vue')['default']
    SuggestionStack: typeof import('./src/components/templates/verifies/TemplateThree/SuggestionStack.vue')['default']
    TemplateOne: typeof import('./src/components/templates/verifies/TemplateOne.vue')['default']
    TemplateThree: typeof import('./src/components/templates/verifies/TemplateThree.vue')['default']
    TemplateTwo: typeof import('./src/components/templates/verifies/TemplateTwo.vue')['default']
    VerifyStack: typeof import('./src/components/templates/verifies/TemplateThree/VerifyStack.vue')['default']
  }
}
