/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CannotAccessVerifyStamp: typeof import('./src/components/common/CannotAccessVerifyStamp.vue')['default']
    CommonContact: typeof import('./src/components/common/CommonContact.vue')['default']
    CommonCustomerProfile: typeof import('./src/components/common/CommonCustomerProfile.vue')['default']
    CommonFooter: typeof import('./src/components/common/CommonFooter.vue')['default']
    CommonSlider: typeof import('./src/components/common/CommonSlider.vue')['default']
    CommonStatusVerify: typeof import('./src/components/common/CommonStatusVerify.vue')['default']
    CompanyContact: typeof import('./src/components/common/CompanyContact.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    FormVerify: typeof import('./src/components/common/FormVerify.vue')['default']
    LoadingOverlay: typeof import('./src/components/elements/LoadingOverlay.vue')['default']
    OldQrcodeTemplate: typeof import('./src/components/templates/verifies/OldQrcodeTemplate.vue')['default']
    ProductDetail: typeof import('./src/components/common/ProductDetail.vue')['default']
    ProductItem: typeof import('./src/components/common/ProductItem.vue')['default']
    QRX_Template_1: typeof import('./src/components/templates/QRX_Template_1.vue')['default']
    QRX_Template_2: typeof import('./src/components/templates/QRX_Template_2.vue')['default']
    RelatedProduct: typeof import('./src/components/common/RelatedProduct.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialChannel: typeof import('./src/components/common/SocialChannel.vue')['default']
    StampCodeBlocked: typeof import('./src/components/common/StampCodeBlocked.vue')['default']
    StampCodeNew: typeof import('./src/components/common/StampCodeNew.vue')['default']
    TemplateOne: typeof import('./src/components/templates/verifies/TemplateOne.vue')['default']
    VerifyTemplateOne: typeof import('./src/components/templates/verifies/VerifyTemplateOne.vue')['default']
  }
}
