name: Deploy QRS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Build Js
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
          BASE_URL: "https://dev.qrx.com.vn/"
          VITE_API_ENDPOINT: "https://dev.qrx.com.vn/"
        run: |
          npm i
          npm run build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "dist/"
          REMOTE_PORT: ${{ secrets.PORT }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ vars.REMOTE_DIRECTORY_QRX }}
          EXCLUDE: "/dist/, /node_modules/"
